# SRCCLR_API_TOKEN nos secrets

name: Veracode SCA (Action)

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v4

      - name: 🧩 Veracode SCA (Agent-Based)
        uses: veracode/veracode-sca@v2.1.9
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: .
          create-issues: false              # Adiciona no github issues as vulnerabilidades achadas em caso de "true"
          # recursive: true                 # Le todos subdiretorios atrás de mais dependencias
          # skip-collectors: "npm,gradle"   # Ignora os coletores determinados ali para caso queira ignorar o gradle mas rodar o npm por exemplo