# APIID e APIKEY nos secrets

name: Veracode AutoPackager + Pipeline Scan + SARIF

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  veracode:
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v4

      - name: 📦 Instalar Veracode CLI
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode --version

      - name: 📁 Auto Packager (gera e renomeia zip)
        id: pack
        shell: bash
        run: |
          set -euo pipefail
          out_dir="veracode-out"
          mkdir -p "$out_dir"

          # Empacota automaticamente (detecta stack)
          ./veracode package --source . --output "$out_dir" --trust

          # Pega o primeiro .zip gerado e renomeia para analysisPack.zip na raiz do workspace
          zip_file=$(find "$out_dir" -maxdepth 1 -type f -name '*.zip' | head -n1)
          if [ -z "${zip_file:-}" ]; then
            echo "Nenhum .zip gerado pelo Auto Packager." >&2
            echo "Conteúdo de $out_dir:"
            ls -lah "$out_dir" || true
            exit 1
          fi

          final_zip="$GITHUB_WORKSPACE/analysisPack.zip"
          mv -f "$zip_file" "$final_zip"
          echo "✅ Pacote final: $final_zip"

          # Exporta para outros passos
          echo "artifact=$final_zip" >> "$GITHUB_OUTPUT"

      - name: 🔍 Veracode Pipeline Scan (gera JSON)
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          file: ${{ steps.pack.outputs.artifact }}
          json_output: true
          json_output_file: results.json

      - name: 🔄 Converter JSON -> SARIF + Upload
        uses: veracode/veracode-pipeline-scan-results-to-sarif@v2.0.3
        with:
          scan-type: pipeline
          pipeline-results-json: results.json
          output-results-sarif: veracode-results.sarif
          githubToken: ${{ github.token }}